package dev.iconpln.mims.data.local.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TAGOMATERIAL_DATA".
 */
@Entity
public class TAGOMaterialData {

    @Id
    private Long id;
    private String noMaterial;
    private String namaMaterial;
    private String qtyMaterial;
    private String unitMaterial;
    private String snMaterial;
    private String inspectionNumber;

    @Generated
    public TAGOMaterialData() {
    }

    public TAGOMaterialData(Long id) {
        this.id = id;
    }

    @Generated
    public TAGOMaterialData(Long id, String noMaterial, String namaMaterial, String qtyMaterial, String unitMaterial, String snMaterial, String inspectionNumber) {
        this.id = id;
        this.noMaterial = noMaterial;
        this.namaMaterial = namaMaterial;
        this.qtyMaterial = qtyMaterial;
        this.unitMaterial = unitMaterial;
        this.snMaterial = snMaterial;
        this.inspectionNumber = inspectionNumber;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNoMaterial() {
        return noMaterial;
    }

    public void setNoMaterial(String noMaterial) {
        this.noMaterial = noMaterial;
    }

    public String getNamaMaterial() {
        return namaMaterial;
    }

    public void setNamaMaterial(String namaMaterial) {
        this.namaMaterial = namaMaterial;
    }

    public String getQtyMaterial() {
        return qtyMaterial;
    }

    public void setQtyMaterial(String qtyMaterial) {
        this.qtyMaterial = qtyMaterial;
    }

    public String getUnitMaterial() {
        return unitMaterial;
    }

    public void setUnitMaterial(String unitMaterial) {
        this.unitMaterial = unitMaterial;
    }

    public String getSnMaterial() {
        return snMaterial;
    }

    public void setSnMaterial(String snMaterial) {
        this.snMaterial = snMaterial;
    }

    public String getInspectionNumber() {
        return inspectionNumber;
    }

    public void setInspectionNumber(String inspectionNumber) {
        this.inspectionNumber = inspectionNumber;
    }

}
