package dev.iconpln.mims.data.local.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TDO_STATUS".
 */
@Entity
public class TDoStatus {

    @Id
    private Long id;
    private String KodeDo;
    private String Keterangan;
    private String BackgroundColor;
    private String TextColor;

    @Generated
    public TDoStatus() {
    }

    public TDoStatus(Long id) {
        this.id = id;
    }

    @Generated
    public TDoStatus(Long id, String KodeDo, String Keterangan, String BackgroundColor, String TextColor) {
        this.id = id;
        this.KodeDo = KodeDo;
        this.Keterangan = Keterangan;
        this.BackgroundColor = BackgroundColor;
        this.TextColor = TextColor;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getKodeDo() {
        return KodeDo;
    }

    public void setKodeDo(String KodeDo) {
        this.KodeDo = KodeDo;
    }

    public String getKeterangan() {
        return Keterangan;
    }

    public void setKeterangan(String Keterangan) {
        this.Keterangan = Keterangan;
    }

    public String getBackgroundColor() {
        return BackgroundColor;
    }

    public void setBackgroundColor(String BackgroundColor) {
        this.BackgroundColor = BackgroundColor;
    }

    public String getTextColor() {
        return TextColor;
    }

    public void setTextColor(String TextColor) {
        this.TextColor = TextColor;
    }

}
