package dev.iconpln.mims.data.local.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TPEJABAT".
*/
public class TPejabatDao extends AbstractDao<TPejabat, Long> {

    public static final String TABLENAME = "TPEJABAT";

    /**
     * Properties of entity TPejabat.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IdPejabat = new Property(1, String.class, "IdPejabat", false, "ID_PEJABAT");
        public final static Property Nama = new Property(2, String.class, "Nama", false, "NAMA");
    }


    public TPejabatDao(DaoConfig config) {
        super(config);
    }
    
    public TPejabatDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TPEJABAT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ID_PEJABAT\" TEXT," + // 1: IdPejabat
                "\"NAMA\" TEXT);"); // 2: Nama
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TPEJABAT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TPejabat entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String IdPejabat = entity.getIdPejabat();
        if (IdPejabat != null) {
            stmt.bindString(2, IdPejabat);
        }
 
        String Nama = entity.getNama();
        if (Nama != null) {
            stmt.bindString(3, Nama);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TPejabat entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String IdPejabat = entity.getIdPejabat();
        if (IdPejabat != null) {
            stmt.bindString(2, IdPejabat);
        }
 
        String Nama = entity.getNama();
        if (Nama != null) {
            stmt.bindString(3, Nama);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TPejabat readEntity(Cursor cursor, int offset) {
        TPejabat entity = new TPejabat( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // IdPejabat
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // Nama
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TPejabat entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdPejabat(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNama(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TPejabat entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TPejabat entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TPejabat entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
