package dev.iconpln.mims.data.local.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TPEJABAT".
 */
@Entity
public class TPejabat {

    @Id
    private Long id;
    private String IdPejabat;
    private String Nama;

    @Generated
    public TPejabat() {
    }

    public TPejabat(Long id) {
        this.id = id;
    }

    @Generated
    public TPejabat(Long id, String IdPejabat, String Nama) {
        this.id = id;
        this.IdPejabat = IdPejabat;
        this.Nama = Nama;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdPejabat() {
        return IdPejabat;
    }

    public void setIdPejabat(String IdPejabat) {
        this.IdPejabat = IdPejabat;
    }

    public String getNama() {
        return Nama;
    }

    public void setNama(String Nama) {
        this.Nama = Nama;
    }

}
