package dev.iconpln.mims.data.local.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TTRANS_MONITORING_PERMINTAAN".
 */
@Entity
public class TTransMonitoringPermintaan {

    @Id
    private Long id;
    private String NoPermintaan;
    private String NoTransaksi;
    private String StorLocTujuanName;
    private String KodePengeluaran;
    private String StorLocTujuan;
    private String CreatedBy;
    private String NoRepackaging;
    private String Plant;
    private String UpdatedBy;
    private String CreatedDate;
    private String UpdatedDate;
    private Integer JumlahKardus;
    private String StorLocAsalName;
    private String TanggalPermintaan;
    private String TanggalPengeluaran;
    private String PlantName;
    private String StorLocAsal;
    private Integer IsActive;
    private Integer IsDone;
    private String ValuationType;
    private String totalQtyPermintaan;
    private String totalScanQty;
    private String noPengiriman;

    @Generated
    public TTransMonitoringPermintaan() {
    }

    public TTransMonitoringPermintaan(Long id) {
        this.id = id;
    }

    @Generated
    public TTransMonitoringPermintaan(Long id, String NoPermintaan, String NoTransaksi, String StorLocTujuanName, String KodePengeluaran, String StorLocTujuan, String CreatedBy, String NoRepackaging, String Plant, String UpdatedBy, String CreatedDate, String UpdatedDate, Integer JumlahKardus, String StorLocAsalName, String TanggalPermintaan, String TanggalPengeluaran, String PlantName, String StorLocAsal, Integer IsActive, Integer IsDone, String ValuationType, String totalQtyPermintaan, String totalScanQty, String noPengiriman) {
        this.id = id;
        this.NoPermintaan = NoPermintaan;
        this.NoTransaksi = NoTransaksi;
        this.StorLocTujuanName = StorLocTujuanName;
        this.KodePengeluaran = KodePengeluaran;
        this.StorLocTujuan = StorLocTujuan;
        this.CreatedBy = CreatedBy;
        this.NoRepackaging = NoRepackaging;
        this.Plant = Plant;
        this.UpdatedBy = UpdatedBy;
        this.CreatedDate = CreatedDate;
        this.UpdatedDate = UpdatedDate;
        this.JumlahKardus = JumlahKardus;
        this.StorLocAsalName = StorLocAsalName;
        this.TanggalPermintaan = TanggalPermintaan;
        this.TanggalPengeluaran = TanggalPengeluaran;
        this.PlantName = PlantName;
        this.StorLocAsal = StorLocAsal;
        this.IsActive = IsActive;
        this.IsDone = IsDone;
        this.ValuationType = ValuationType;
        this.totalQtyPermintaan = totalQtyPermintaan;
        this.totalScanQty = totalScanQty;
        this.noPengiriman = noPengiriman;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNoPermintaan() {
        return NoPermintaan;
    }

    public void setNoPermintaan(String NoPermintaan) {
        this.NoPermintaan = NoPermintaan;
    }

    public String getNoTransaksi() {
        return NoTransaksi;
    }

    public void setNoTransaksi(String NoTransaksi) {
        this.NoTransaksi = NoTransaksi;
    }

    public String getStorLocTujuanName() {
        return StorLocTujuanName;
    }

    public void setStorLocTujuanName(String StorLocTujuanName) {
        this.StorLocTujuanName = StorLocTujuanName;
    }

    public String getKodePengeluaran() {
        return KodePengeluaran;
    }

    public void setKodePengeluaran(String KodePengeluaran) {
        this.KodePengeluaran = KodePengeluaran;
    }

    public String getStorLocTujuan() {
        return StorLocTujuan;
    }

    public void setStorLocTujuan(String StorLocTujuan) {
        this.StorLocTujuan = StorLocTujuan;
    }

    public String getCreatedBy() {
        return CreatedBy;
    }

    public void setCreatedBy(String CreatedBy) {
        this.CreatedBy = CreatedBy;
    }

    public String getNoRepackaging() {
        return NoRepackaging;
    }

    public void setNoRepackaging(String NoRepackaging) {
        this.NoRepackaging = NoRepackaging;
    }

    public String getPlant() {
        return Plant;
    }

    public void setPlant(String Plant) {
        this.Plant = Plant;
    }

    public String getUpdatedBy() {
        return UpdatedBy;
    }

    public void setUpdatedBy(String UpdatedBy) {
        this.UpdatedBy = UpdatedBy;
    }

    public String getCreatedDate() {
        return CreatedDate;
    }

    public void setCreatedDate(String CreatedDate) {
        this.CreatedDate = CreatedDate;
    }

    public String getUpdatedDate() {
        return UpdatedDate;
    }

    public void setUpdatedDate(String UpdatedDate) {
        this.UpdatedDate = UpdatedDate;
    }

    public Integer getJumlahKardus() {
        return JumlahKardus;
    }

    public void setJumlahKardus(Integer JumlahKardus) {
        this.JumlahKardus = JumlahKardus;
    }

    public String getStorLocAsalName() {
        return StorLocAsalName;
    }

    public void setStorLocAsalName(String StorLocAsalName) {
        this.StorLocAsalName = StorLocAsalName;
    }

    public String getTanggalPermintaan() {
        return TanggalPermintaan;
    }

    public void setTanggalPermintaan(String TanggalPermintaan) {
        this.TanggalPermintaan = TanggalPermintaan;
    }

    public String getTanggalPengeluaran() {
        return TanggalPengeluaran;
    }

    public void setTanggalPengeluaran(String TanggalPengeluaran) {
        this.TanggalPengeluaran = TanggalPengeluaran;
    }

    public String getPlantName() {
        return PlantName;
    }

    public void setPlantName(String PlantName) {
        this.PlantName = PlantName;
    }

    public String getStorLocAsal() {
        return StorLocAsal;
    }

    public void setStorLocAsal(String StorLocAsal) {
        this.StorLocAsal = StorLocAsal;
    }

    public Integer getIsActive() {
        return IsActive;
    }

    public void setIsActive(Integer IsActive) {
        this.IsActive = IsActive;
    }

    public Integer getIsDone() {
        return IsDone;
    }

    public void setIsDone(Integer IsDone) {
        this.IsDone = IsDone;
    }

    public String getValuationType() {
        return ValuationType;
    }

    public void setValuationType(String ValuationType) {
        this.ValuationType = ValuationType;
    }

    public String getTotalQtyPermintaan() {
        return totalQtyPermintaan;
    }

    public void setTotalQtyPermintaan(String totalQtyPermintaan) {
        this.totalQtyPermintaan = totalQtyPermintaan;
    }

    public String getTotalScanQty() {
        return totalScanQty;
    }

    public void setTotalScanQty(String totalScanQty) {
        this.totalScanQty = totalScanQty;
    }

    public String getNoPengiriman() {
        return noPengiriman;
    }

    public void setNoPengiriman(String noPengiriman) {
        this.noPengiriman = noPengiriman;
    }

}
